name: Create release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        #        when ./changelog/${GITHUB_REF/refs\/tags\//}/version-summary.md will be added to keep-changelog plugin
        #        with:
        #          body_path: ./changelog/${GITHUB_REF/refs\/tags\//}/version-summary.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}